/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    brands: Brand;
    locations: Location;
    clinics: Clinic;
    reviews: Review;
    photos: Photo;
    qa: Qa;
    authors: Author;
    'medical-reviewers': MedicalReviewer;
    guides: Guide;
    news: News;
    faqs: Faq;
    'before-after-cases': BeforeAfterCase;
    bookings: Booking;
    promotions: Promotion;
    'audit-logs': AuditLog;
    'data-alerts': DataAlert;
    'export-jobs': ExportJob;
    'scan-jobs': ScanJob;
    'assistant-logs': AssistantLog;
    'page-index': PageIndex;
    claims: Claim;
    'claim-invites': ClaimInvite;
    subscribers: Subscriber;
    'zip-codes': ZipCode;
    'video-testimonials': VideoTestimonial;
    'social-posts': SocialPost;
    'internal-link-suggestions': InternalLinkSuggestion;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    clinics: ClinicsSelect<false> | ClinicsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    qa: QaSelect<false> | QaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'medical-reviewers': MedicalReviewersSelect<false> | MedicalReviewersSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'before-after-cases': BeforeAfterCasesSelect<false> | BeforeAfterCasesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'data-alerts': DataAlertsSelect<false> | DataAlertsSelect<true>;
    'export-jobs': ExportJobsSelect<false> | ExportJobsSelect<true>;
    'scan-jobs': ScanJobsSelect<false> | ScanJobsSelect<true>;
    'assistant-logs': AssistantLogsSelect<false> | AssistantLogsSelect<true>;
    'page-index': PageIndexSelect<false> | PageIndexSelect<true>;
    claims: ClaimsSelect<false> | ClaimsSelect<true>;
    'claim-invites': ClaimInvitesSelect<false> | ClaimInvitesSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'zip-codes': ZipCodesSelect<false> | ZipCodesSelect<true>;
    'video-testimonials': VideoTestimonialsSelect<false> | VideoTestimonialsSelect<true>;
    'social-posts': SocialPostsSelect<false> | SocialPostsSelect<true>;
    'internal-link-suggestions': InternalLinkSuggestionsSelect<false> | InternalLinkSuggestionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'header-config': HeaderConfig;
    'site-config': SiteConfig;
  };
  globalsSelect: {
    'header-config': HeaderConfigSelect<false> | HeaderConfigSelect<true>;
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Staff, clinic owner, brand and customer accounts. Role controls access; only admins and editors can change a role.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor' | 'user' | 'clinic' | 'brand') | null;
  /**
   * Set on claim approval. The clinic profile this user can edit.
   */
  linkedClinic?: (number | null) | Clinic;
  /**
   * Set on claim approval. The brand this user can manage.
   */
  linkedBrand?: (number | null) | Brand;
  /**
   * Clinics this user saved from the directory. Editable by the user on /profile.
   */
  savedClinics?: (number | Clinic)[] | null;
  /**
   * Treatment slug saved from the candidate quiz, surfaced as "recommended for you" on /profile. Not medical advice.
   */
  quizRecommendation?: string | null;
  setupToken?: string | null;
  setupTokenExpiry?: string | null;
  /**
   * Set by /api/auth/verify-signup once the emailed 6-digit code is confirmed. Gates login (see beforeLogin hook).
   */
  emailVerified?: boolean | null;
  verificationCode?: string | null;
  verificationCodeExpiry?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Physical clinic locations. Ratings come from imported reviews and are read-only. Each clinic is its own page and location.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinics".
 */
export interface Clinic {
  id: number;
  clinicName: string;
  slug: string;
  tagline?: string | null;
  description?: string | null;
  clinicType?: ('medspa' | 'dermatology' | 'plastic-surgery' | 'dental-aesthetics' | 'other') | null;
  acceptsInsurance?: boolean | null;
  /**
   * Semicolon list.
   */
  paymentMethods?: string | null;
  /**
   * Semicolon list.
   */
  amenities?: string | null;
  /**
   * Computed from imported reviews. Not hand-editable (trust signal).
   */
  aggregateRating?: number | null;
  /**
   * Number of reviews behind the rating. Set by import.
   */
  aggregateRatingCount?: number | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city: string;
  state: string;
  zip?: string | null;
  neighborhood?: string | null;
  county?: string | null;
  country?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  googlePlaceId?: string | null;
  googleMapsUrl?: string | null;
  directionsUrl?: string | null;
  appleMapsUrl?: string | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Off by default. Phone, website and social are public for every clinic, but a scraped email is never published until the owner claims the profile and turns this on themselves.
   */
  emailPublic?: boolean | null;
  websiteUrl?: string | null;
  bookingUrl?: string | null;
  instagramUrl?: string | null;
  tiktokUrl?: string | null;
  facebookUrl?: string | null;
  linkedinUrl?: string | null;
  youtubeUrl?: string | null;
  hoursJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Product brands this clinic uses (e.g., Botox, Juvederm, Dysport).
   */
  brandsOffered?: (number | Brand)[] | null;
  /**
   * Service areas this clinic provides (e.g., Lip Filler, Cheek Filler).
   */
  servicesOffered?: (number | Service)[] | null;
  /**
   * Lowest service price shown on listing cards.
   */
  startingPrice?: number | null;
  logoUrl?: string | null;
  clinicPhotoUrls?:
    | {
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Set automatically from clinicPhotoUrls. Used for listing order.
   */
  hasPhoto?: boolean | null;
  /**
   * Uploaded clinic photos (gallery). When set, these are shown instead of the legacy clinicPhotoUrls. A claimed clinic owner can upload these from their dashboard.
   */
  photos?: (number | Media)[] | null;
  /**
   * Plan tier for this clinic. Entitlement for clinic-level features derives from the claimed-owner provider's tier.
   */
  subscriptionTier?: ('free' | 'starter' | 'pro' | 'elite') | null;
  /**
   * Billing status. Set manually for now (manual billing v1); Stripe self-serve later.
   */
  subscriptionStatus?: ('none' | 'active' | 'past_due' | 'canceled') | null;
  /**
   * Set automatically when a claim is approved. Not hand-editable.
   */
  claimed?: boolean | null;
  /**
   * The user who claimed this profile. Set on claim approval.
   */
  claimedBy?: (number | null) | User;
  /**
   * Unique import ID from the CSV scrape (e.g. "clinic-ca-00001"). Set by the importer automatically. Never edit this field manually — it is used for upsert deduplication.
   */
  clinicId: string;
  /**
   * Set by the data importer to group a batch (for scoped re-import / wipe). Not hand-editable.
   */
  importBatch?: string | null;
  lastScrapedDate?: string | null;
  sourceUrls?:
    | {
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'published' | 'review' | 'draft';
  /**
   * BUILD BUDGET ONLY -- nothing to do with SEO, despite the column name. When checked, this clinic is left out of the pages pre-rendered at build time (it still renders on demand). Bulk uploads default to checked so a 39k-clinic import cannot blow up the build. Indexing is controlled entirely in SEO > URLs. Until 2026-08-08 this field ALSO silently gated the clinic sitemap, which is why zero clinic urls were ever submitted to Google; the sitemap now reads the url registry instead.
   */
  noindex?: boolean | null;
  /**
   * Set when a staged clinic is approved. Draft clinics are never shown publicly.
   */
  publishedAt?: string | null;
  /**
   * Scraper confidence score. 100 = fully verified.
   */
  dataConfidence?: number | null;
  /**
   * Flag set by importer when data looks uncertain.
   */
  needsManualReview?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Aesthetic product brands (e.g., Botox, Juvederm, Dysport, Daxxify). Clinics list which brands they carry via brandsOffered. Each brand gets its own /brands/[slug] path.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  slug: string;
  /**
   * e.g. Allergan Aesthetics, Galderma, Merz, Revance
   */
  manufacturer?: string | null;
  category: 'neurotoxin' | 'filler' | 'biostimulator' | 'skin' | 'body' | 'other';
  tagline?: string | null;
  shortDescription?: string | null;
  /**
   * Pillar guide for this brand.
   */
  guide?: (number | null) | Guide;
  avgPriceFromUsd?: number | null;
  avgPriceToUsd?: number | null;
  priceUnit?: ('per_unit' | 'per_session' | 'per_syringe') | null;
  /**
   * Phosphor icon slug.
   */
  iconSlug?: string | null;
  /**
   * e.g. "3 to 4 months"
   */
  longevityLabel?: string | null;
  longevityMonthsMin?: number | null;
  longevityMonthsMax?: number | null;
  /**
   * e.g. "0 to 24 hours"
   */
  downtimeLabel?: string | null;
  downtimeHoursMax?: number | null;
  websiteUrl?: string | null;
  logoUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Long-form treatment guides and articles. Search engine title and description are in the Meta tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  title: string;
  slug: string;
  /**
   * Hero subhead, 1 to 2 sentences.
   */
  lede: string;
  /**
   * Short summary for listing cards and search snippets (under 200 characters). Also used as the default meta description.
   */
  excerpt?: string | null;
  /**
   * Upload the cover image directly. Drag and drop a file or pick from the media library.
   */
  coverImage?: (number | null) | Media;
  /**
   * Legacy / external cover image URL. Used only if no cover image is uploaded above.
   */
  coverImageUrl?: string | null;
  category: 'treatment-guide' | 'article' | 'expert-qa' | 'cost-report';
  relatedService?: (number | null) | Service;
  readTimeMin?: number | null;
  sourcesCount?: number | null;
  author: number | Author;
  medicalReviewer?: (number | null) | MedicalReviewer;
  lastMedicallyReviewed?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 40-80 word answer-first summary shown at the top of the guide for featured snippets.
   */
  answerSnippet?: string | null;
  /**
   * Array of short facts, e.g. ["Fact 1", "Fact 2"]. Rendered as a bullet list above the body.
   */
  atAGlance?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Inline array of {question, answer, detail?, offLabel?, safetyFlag?} for imported FAQ content. Shown alongside the existing faqs relationship.
   */
  faq?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of {title, publisher, url, publishedDate, sourceType, claimsSupported[]} objects. Rendered as a citations block.
   */
  sources?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of {anchorText, targetType, targetSlug, targetPath, paragraphIndex} objects. Each one is rendered as a real inline link inside body at the paragraph matching anchorText, with a hover preview card. Populated by the internal-linking agent (editorial-seeded or AI-discovered) after admin approval, or hand-edited here.
   */
  internalLinks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Set automatically once the internal-linking discovery agent has scanned this page, so repeat scans skip it (whether or not it produced any suggestions). Clear this to force a re-scan.
   */
  linkDiscoveryScannedAt?: string | null;
  /**
   * Primary target keyword for this page, shown in the admin Content Report SEO table.
   */
  focusKeyword?: string | null;
  faqs?: (number | Faq)[] | null;
  featured?: boolean | null;
  publishedAt?: string | null;
  /**
   * Only Published guides can appear publicly, and only after reviewStatus is Approved.
   */
  status: 'draft' | 'published';
  /**
   * Gate: only Approved guides are visible to the public. Change this field directly, or select multiple rows in the list view and use bulk edit.
   */
  reviewStatus: 'imported' | 'in-review' | 'approved';
  /**
   * DEPRECATED and no longer read by anything (2026-08-08). Indexing for every url now lives in SEO > URLs, and guides are batched in from the Indexing screen like any other page type. Kept only so historical values are not lost; this field no longer affects the sitemap or the page's robots tag.
   */
  indexState: 'noindex' | 'indexed';
  /**
   * DEPRECATED and no longer read (2026-08-08). It duplicated the index gate and could emit a robots tag contradicting the registry. Queued urls already emit noindex,follow so internal links stay discoverable.
   */
  nofollow?: boolean | null;
  /**
   * Stamped by the content importer. Use to identify which batch this item came from.
   */
  importBatch?: string | null;
  /**
   * Set automatically when approved.
   */
  approvedAt?: string | null;
  /**
   * Set automatically when approved.
   */
  approvedBy?: (number | null) | User;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload images here. Drag and drop, or click to browse.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO. Required.
   */
  alt: string;
  /**
   * Optional caption shown beneath the image in articles.
   */
  caption?: string | null;
  /**
   * Optional photo credit or source attribution.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Aesthetic service areas (e.g., Lip Filler, Cheek Filler, Masseter Botox). Clinics list which services they offer via servicesOffered. Each service gets its own /services/[slug] path.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  slug: string;
  category: 'body-area' | 'skin' | 'thread' | 'body' | 'other';
  tagline?: string | null;
  shortDescription?: string | null;
  bodyAreas?:
    | (
        | 'forehead'
        | 'brow'
        | 'under-eye'
        | 'crows-feet'
        | 'cheeks'
        | 'lips'
        | 'chin'
        | 'jawline'
        | 'neck'
        | 'decolletage'
      )[]
    | null;
  /**
   * Product brands commonly used for this service (e.g., Lip Filler → Juvederm, Sculptra).
   */
  relatedBrands?: (number | Brand)[] | null;
  /**
   * Pillar guide for this service.
   */
  guide?: (number | null) | Guide;
  avgPriceFromUsd?: number | null;
  avgPriceToUsd?: number | null;
  priceUnit?: ('per_unit' | 'per_session' | 'per_syringe') | null;
  /**
   * Phosphor icon slug.
   */
  iconSlug?: string | null;
  /**
   * 0 (none) to 10 (severe).
   */
  painIndex?: number | null;
  /**
   * e.g. "3 to 4 months"
   */
  longevityLabel?: string | null;
  longevityMonthsMin?: number | null;
  longevityMonthsMax?: number | null;
  /**
   * e.g. "0 to 24 hours"
   */
  downtimeLabel?: string | null;
  downtimeHoursMax?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Editorial bylines shown on guides and articles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  fullName: string;
  slug: string;
  role?: string | null;
  bio?: string | null;
  photoUrl?: string | null;
  linkedinUrl?: string | null;
  twitterUrl?: string | null;
  articleCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Board-certified reviewers credited on medically reviewed content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-reviewers".
 */
export interface MedicalReviewer {
  id: number;
  fullName: string;
  slug: string;
  credentials: 'MD' | 'DO' | 'NP' | 'PA' | 'RN' | 'DDS' | 'PhD';
  title: string;
  city?: string | null;
  state?: string | null;
  bio?: string | null;
  photoUrl?: string | null;
  npiNumber?: string | null;
  boardCertifications?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  linkedinUrl?: string | null;
  reviewedCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable FAQ entries that feed FAQ schema on the matching pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  /**
   * 40 to 80 words ideal for AEO snippets.
   */
  answer: string;
  /**
   * Optional 90-140 word long-form detail shown below the short answer. Included alongside the short answer in the FAQPage acceptedAnswer.text.
   */
  answerDetail?: string | null;
  /**
   * Which page type this FAQ primarily belongs to. Service and Location can both be set on the same FAQ to narrow it further (e.g. a Botox FAQ specific to New York).
   */
  scope: 'homepage' | 'service' | 'brand' | 'guide' | 'location' | 'clinic-type';
  /**
   * Set when scope is Service, or to narrow a Location-scoped FAQ to one treatment.
   */
  service?: (number | null) | Service;
  /**
   * Set when scope is Brand, or to narrow a Location-scoped FAQ to one brand.
   */
  brand?: (number | null) | Brand;
  /**
   * Set when scope is Guide -- this FAQ appears directly on that guide page (via getGuideOwnFaqs), for topics that have no matching Service or Brand page (e.g. Jowls, Hyaluronidase). Distinct from "relatedGuide" below, which is a "read the full guide" link on a Service/Brand-scoped FAQ, not the FAQ's own page.
   */
  guide?: (number | null) | Guide;
  /**
   * Set when scope is Location. Works for both a state and a metro/city, since Locations already models that hierarchy.
   */
  location?: (number | null) | Location;
  /**
   * Set when scope is Clinic type.
   */
  clinicType?: ('plastic-surgery' | 'dermatology' | 'dental-aesthetics' | 'medspa' | 'other') | null;
  /**
   * "Read the full guide" link target.
   */
  relatedGuide?: (number | null) | Guide;
  /**
   * Check if this FAQ discusses an off-label use of a treatment or product. Renders an inline notice on the page.
   */
  offLabel?: boolean | null;
  /**
   * Flags medical safety context that must render as an inline notice per brand voice rules (§4.1).
   */
  safetyFlag?: ('none' | 'serious-risk' | 'non-fda-approved') | null;
  sortRank?: number | null;
  /**
   * Stable id used by the bulk uploader to match this FAQ on re-upload. Auto-generated from the question if left blank.
   */
  stableId?: string | null;
  /**
   * Gate: only Approved FAQs appear on the live site. Bulk-uploaded FAQs start as Imported until approved.
   */
  reviewStatus: 'imported' | 'approved';
  /**
   * Stamped by the bulk uploader. Identifies which upload batch this FAQ came from.
   */
  importBatch?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * States, metros, cities, and neighborhoods. "Market is live" is computed automatically by the page scan. Use the "Hide from search engines" sidebar toggle to control indexing manually.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  slug: string;
  kind: 'country' | 'state' | 'metro' | 'city' | 'neighborhood';
  /**
   * 2-letter state code.
   */
  state?: string | null;
  parent?: (number | null) | Location;
  latitude?: number | null;
  longitude?: number | null;
  imageUrl?: string | null;
  providerCount?: number | null;
  sortRank?: number | null;
  featured?: boolean | null;
  /**
   * Computed automatically by `npm run scan:pages` based on whether this market has >=1 published clinic. Not editable here -- any manual change would be overwritten on the next scan.
   */
  isLive?: boolean | null;
  /**
   * BUILD BUDGET ONLY -- the name is historical. When checked, this market's hub page is left out of the pages pre-rendered at build time (it still renders on demand). The old description claimed it also excluded the page from sitemap.xml; that was never true -- state and city hub urls come from the url registry. Indexing is controlled entirely in SEO > URLs.
   */
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Clinic reviews imported from source platforms. Reviews attach to clinics only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  reviewId: string;
  clinic?: (number | null) | Clinic;
  rating: number;
  title?: string | null;
  excerpt?: string | null;
  text?: string | null;
  publishStatus?: ('full' | 'excerpt_only' | 'hidden') | null;
  serviceTag?: string | null;
  reviewDate?: string | null;
  sourcePlatform?: string | null;
  sourceReviewId?: string | null;
  sourceUrl?: string | null;
  attributionRequired?: boolean | null;
  responseFromProvider?: string | null;
  responseDate?: string | null;
  matchConfidence?: number | null;
  needsManualReview?: boolean | null;
  /**
   * Stamped by the bulk uploader/importer so a staged upload can be approved together.
   */
  importBatch?: string | null;
  moderationStatus?: ('pending' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Provider and clinic photos. Only photos with documented consent may be shown publicly.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  photoId: string;
  clinic?: (number | null) | Clinic;
  serviceTag?: string | null;
  photoUrl: string;
  type:
    | 'before'
    | 'after'
    | 'headshot'
    | 'clinic_interior'
    | 'clinic_exterior'
    | 'treatment_room'
    | 'team'
    | 'equipment';
  /**
   * Same id on a before + after pair.
   */
  pairId?: string | null;
  weeksPostTreatment?: number | null;
  caption?: string | null;
  consentDocumented?: boolean | null;
  sourcePlatform: 'clinic_site' | 'google' | 'instagram' | 'injectors_world';
  sourceUrl: string;
  /**
   * Set by the data importer to group a batch (for scoped re-import / wipe). Not hand-editable.
   */
  importBatch?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reader questions. Set status to Answered and add an answer to publish it to /questions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qa".
 */
export interface Qa {
  id: number;
  qaId: string;
  /**
   * URL slug. Auto-generated on submission.
   */
  slug?: string | null;
  status: 'new' | 'answered' | 'rejected';
  questionTitle: string;
  questionText?: string | null;
  /**
   * Name of the person who answered.
   */
  answeredByName?: string | null;
  /**
   * The answer. Required before publishing.
   */
  answerText?: string | null;
  serviceTag?: string | null;
  cityTag?: string | null;
  sourcePlatform?: ('clinic_blog' | 'forum' | 'directory' | 'injectors_world' | 'user_submission') | null;
  sourceUrl?: string | null;
  date?: string | null;
  /**
   * Email from public submission (not displayed publicly).
   */
  submitterEmail?: string | null;
  /**
   * Set by the data importer to group a batch (for scoped re-import / wipe). Not hand-editable.
   */
  importBatch?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Timely news articles: treatment updates, industry news, company announcements. Keep separate from evergreen Guides.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * URL-safe slug, e.g. fda-approves-new-filler. Auto-generate from title.
   */
  slug: string;
  /**
   * Short summary for listing cards, RSS feed, and newsletter sends. Under 300 characters.
   */
  excerpt: string;
  /**
   * Upload cover image. 16:9 or wider recommended. Served from R2.
   */
  coverImage?: (number | null) | Media;
  /**
   * Legacy or external cover image URL. Only used when no file is uploaded above.
   */
  coverImageUrl?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 40-80 word answer-first summary shown at the top of the article for featured snippets.
   */
  answerSnippet?: string | null;
  /**
   * Array of short facts, e.g. ["Fact 1", "Fact 2"]. Rendered as a bullet list above the body.
   */
  atAGlance?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of {question, answer} objects for the FAQ accordion and FAQPage JSON-LD.
   */
  faq?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of {title, publisher, url, publishedDate, sourceType, claimsSupported[]} objects. Rendered as a citations block.
   */
  sources?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Array of {anchorText, targetType, targetSlug, targetPath, paragraphIndex} objects. Each one is rendered as a real inline link inside body at the paragraph matching anchorText, with a hover preview card. Populated by the internal-linking agent (editorial-seeded or AI-discovered) after admin approval, or hand-edited here.
   */
  internalLinks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Set automatically once the internal-linking discovery agent has scanned this page, so repeat scans skip it (whether or not it produced any suggestions). Clear this to force a re-scan.
   */
  linkDiscoveryScannedAt?: string | null;
  /**
   * Primary target keyword for this page, shown in the admin Content Report SEO table.
   */
  focusKeyword?: string | null;
  category: 'treatment-update' | 'industry' | 'company' | 'announcement' | 'product-launch' | 'research' | 'regulation';
  author: number | Author;
  /**
   * Optional. Add only when the article covers clinical or safety content.
   */
  medicalReviewer?: (number | null) | MedicalReviewer;
  publishedAt?: string | null;
  /**
   * Optional. Links to a service pillar page from the article.
   */
  relatedService?: (number | null) | Service;
  /**
   * Only Published articles appear on the site. Kept in sync with Review Status: approving sets this to Published.
   */
  status: 'draft' | 'published';
  /**
   * Pin this article to the top of the news index.
   */
  featured?: boolean | null;
  /**
   * Gate: only Approved articles are visible to the public. Change this field directly, or select multiple rows in the list view and use bulk edit.
   */
  reviewStatus: 'imported' | 'in-review' | 'approved';
  /**
   * DEPRECATED and no longer read by anything (2026-08-08). Indexing for every url now lives in SEO > URLs, and articles are batched in from the Indexing screen like any other page type. Kept only so historical values are not lost; this field no longer affects the sitemap or the page's robots tag.
   */
  indexState: 'noindex' | 'indexed';
  /**
   * When checked, the page emits nofollow in its robots meta tag. Cleared automatically when drip-indexed.
   */
  nofollow?: boolean | null;
  /**
   * Stamped by the content importer. Use to identify which batch this item came from.
   */
  importBatch?: string | null;
  /**
   * Set automatically when approved.
   */
  approvedAt?: string | null;
  /**
   * Set automatically when approved.
   */
  approvedBy?: (number | null) | User;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Before and after cases. Only cases with consent granted are shown publicly.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-after-cases".
 */
export interface BeforeAfterCase {
  id: number;
  caseTitle: string;
  beforePhotoUrl: string;
  afterPhotoUrl: string;
  /**
   * Botox, Lip Filler, etc.
   */
  serviceTag: string;
  /**
   * Weeks between before and after.
   */
  weeksPost: number;
  city?: string | null;
  state?: string | null;
  patientNote?: string | null;
  consentGranted: boolean;
  featured?: boolean | null;
  sortRank?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Booking and lead requests from the site. Read the request, then set the status (new → confirmed → completed). Patient contact details are staff-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  patientName: string;
  patientEmail: string;
  patientPhone?: string | null;
  clinic?: (number | null) | Clinic;
  service?: (number | null) | Service;
  serviceTag?: string | null;
  preferredDate?: string | null;
  preferredTime?: string | null;
  message?: string | null;
  consentToContact: boolean;
  status: 'new' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
  source?: ('website' | 'hero_search' | 'provider_profile' | 'guide_cta' | 'lead_form') | null;
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Internal notes by editors.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Three placement types per scope:
 *   banner — max 1 active per scope. Needs image + link.
 *   sponsored-card — max 3 per scope. Promotes a clinic.
 *   featured-pin — max 3 per scope. Pins to top of organic list (positions 1-3).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  /**
   * Internal label e.g. "Botox Houston Q3 2026".
   */
  title: string;
  status: 'draft' | 'active' | 'paused' | 'expired';
  /**
   * Where this promotion appears on listing pages.
   */
  placement: 'banner' | 'sponsored-card' | 'featured-pin';
  /**
   * Which pages this promotion appears on. ZIP-radius scopes match a visitor's resolved location, not a fixed page, and currently only support the "banner" placement.
   */
  scope: 'national' | 'service' | 'state' | 'city' | 'service+state' | 'service+city' | 'zip' | 'service+zip';
  /**
   * Required when scope includes a service.
   */
  service?: (number | null) | Service;
  /**
   * State location. Required when scope = state or service+state.
   */
  state?: (number | null) | Location;
  /**
   * City location (kind = city or metro). Required when scope = city or service+city.
   */
  city?: (number | null) | Location;
  /**
   * Anchor ZIP code. Required when scope = zip or service+zip. The promotion is shown to visitors resolved within Zip Radius Miles of this ZIP's centroid.
   */
  zipScope?: (number | null) | ZipCode;
  /**
   * Radius in miles around Zip Scope. Required when scope = zip or service+zip. Between 1 and 50.
   */
  zipRadiusMiles?: number | null;
  /**
   * The clinic to promote.
   */
  clinic?: (number | null) | Clinic;
  /**
   * Display position 1, 2, or 3 within the sponsored / featured section.
   */
  featuredRank?: number | null;
  /**
   * Banner image. Required for banner placement. Recommended size: 1200 × 200 px (6:1).
   */
  bannerImage?: (number | null) | Media;
  /**
   * Destination URL when the banner is clicked (opens in new tab). Required for banner.
   */
  bannerLinkUrl?: string | null;
  /**
   * Alt text for the banner image (accessibility).
   */
  bannerAltText?: string | null;
  startDate?: string | null;
  /**
   * Auto-expires after this date. Leave blank for no expiry.
   */
  endDate?: string | null;
  /**
   * Internal billing / contact notes. Not shown publicly.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * US ZIP code centroids (GeoNames, public domain). Seeded via `npm run seed:zips`. Read-only reference used for ZIP search resolution and ZIP featuring.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zip-codes".
 */
export interface ZipCode {
  id: number;
  /**
   * 5-digit US ZIP code.
   */
  zip: string;
  city: string;
  /**
   * 2-letter state code (e.g. NY).
   */
  state: string;
  county?: string | null;
  /**
   * The matching state/metro Location for this ZIP, set by scripts/backfill-zip-locations.ts. Null for ZIPs with no match (military APO/FPO, territories, or a city not yet in Locations).
   */
  location?: (number | null) | Location;
  /**
   * Latitude of the ZIP centroid.
   */
  lat: number;
  /**
   * Longitude of the ZIP centroid.
   */
  lng: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Read-only history of every create, update, and delete on tracked collections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: 'create' | 'update' | 'delete';
  collectionSlug: string;
  documentId?: string | null;
  documentTitle?: string | null;
  /**
   * Who performed the action, or "system" for automated/public writes.
   */
  userEmail?: string | null;
  userId?: string | null;
  summary?: string | null;
  /**
   * Field names that changed (updates only).
   */
  changedFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Data integrity and operational alerts. Resolve or acknowledge each one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-alerts".
 */
export interface DataAlert {
  id: number;
  /**
   * Set by the import / scan automation so re-scans update instead of duplicating. Not hand-editable.
   */
  alertKey: string;
  type:
    | 'duplicate_clinic'
    | 'duplicate_provider'
    | 'missing_coordinates'
    | 'missing_source'
    | 'unknown_treatment'
    | 'broken_relationship'
    | 'unmatched_city'
    | 'missing_trust_field'
    | 'invalid_zip'
    | 'zip_location_mismatch'
    | 'invalid_coordinates'
    | 'invalid_phone'
    | 'duplicate_npi'
    | 'possible_branch'
    | 'orphaned_promotion'
    | 'promo_missing_provider'
    | 'promo_missing_image'
    | 'promo_expired'
    | 'promo_scope_mismatch'
    | 'zip_feature_request'
    | 'content_missing_reviewer'
    | 'content_missing_author'
    | 'content_few_sources'
    | 'content_missing_cover'
    | 'content_validation_error'
    | 'content_duplicate_slug'
    | 'promo_expiring_soon'
    | 'promo_slot_exceeded'
    | 'new_indexable_page'
    | 'other';
  severity: 'error' | 'warning' | 'info';
  message: string;
  collectionSlug?: string | null;
  /**
   * Business id (e.g. providerId / clinicId) or DB id.
   */
  documentId?: string | null;
  /**
   * The other record involved (for duplicates / relationships).
   */
  relatedId?: string | null;
  /**
   * What raised it: "import" or "scan".
   */
  source?: string | null;
  status: 'open' | 'acknowledged' | 'resolved';
  updatedAt: string;
  createdAt: string;
}
/**
 * History and progress of admin data exports. Created automatically, not by hand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "export-jobs".
 */
export interface ExportJob {
  id: number;
  /**
   * Which collection this export covers.
   */
  collectionSlug: 'clinics' | 'guides' | 'news' | 'faqs' | 'brands' | 'services' | 'all';
  status: 'queued' | 'running' | 'done' | 'failed' | 'abandoned';
  /**
   * State / city / brand / service the export was scoped to. Empty means everything.
   */
  filters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Human-readable version of the filters, for the history list.
   */
  filterSummary?: string | null;
  /**
   * Counted up front so progress has a denominator.
   */
  totalRows?: number | null;
  /**
   * Updated once per batch while the job runs.
   */
  processedRows?: number | null;
  fileName?: string | null;
  /**
   * Download link. Empty until the job finishes.
   */
  fileUrl?: string | null;
  fileSizeBytes?: number | null;
  /**
   * Failure reason, if the job failed.
   */
  error?: string | null;
  startedBy?: (number | null) | User;
  startedAt?: string | null;
  finishedAt?: string | null;
  heartbeatAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * History and live progress of url registry scans. Created automatically, not by hand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scan-jobs".
 */
export interface ScanJob {
  id: number;
  status: 'queued' | 'running' | 'done' | 'failed' | 'abandoned';
  /**
   * Which stage the run is in. A full scan has several, and the slow one is the upsert.
   */
  phase?: string | null;
  trigger?: ('admin' | 'cli') | null;
  /**
   * Urls the scan intends to write. Only known once the build phase finishes, so it is empty at first.
   */
  totalRows?: number | null;
  /**
   * Updated every few batches while the job runs.
   */
  processedRows?: number | null;
  /**
   * Urls seen for the first time.
   */
  createdRows?: number | null;
  /**
   * Urls that already existed and were refreshed.
   */
  updatedRows?: number | null;
  /**
   * Urls that no longer have anything to show, so they dropped out of the sitemap. Their indexing decision is preserved.
   */
  lostDataRows?: number | null;
  /**
   * Rows that could not be written. Any failure here SKIPS the lost-data reconcile, because a failed batch is indistinguishable from a url that vanished.
   */
  failedRows?: number | null;
  /**
   * Published clinics whose city and state match no Location, so no url could be built for them.
   */
  unmappedClinics?: number | null;
  /**
   * How many urls each source contributed. A source at zero means it produced nothing.
   */
  bySource?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Urls in the sitemap after this run.
   */
  indexedNow?: number | null;
  /**
   * Urls waiting for a batch after this run.
   */
  queuedNow?: number | null;
  /**
   * Markets that went from Coming Soon to a real directory. Liveness is automatic; indexing is not.
   */
  marketsFlippedLive?: number | null;
  marketsFlippedComingSoon?: number | null;
  /**
   * Failure reason, if the job failed.
   */
  error?: string | null;
  startedBy?: (number | null) | User;
  startedAt?: string | null;
  finishedAt?: string | null;
  heartbeatAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * AI assistant conversation log. Read-only audit trail; also powers the monthly spend cap and per-IP daily limit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant-logs".
 */
export interface AssistantLog {
  id: number;
  /**
   * The visitor's message (truncated).
   */
  query?: string | null;
  ip?: string | null;
  tokensIn?: number | null;
  tokensOut?: number | null;
  /**
   * Estimated USD cost of this exchange.
   */
  estimatedCostUsd?: number | null;
  /**
   * Comma-separated tool names called for this exchange.
   */
  toolsUsed?: string | null;
  /**
   * True when the assistant declined an off-topic or out-of-scope request.
   */
  flagged?: boolean | null;
  /**
   * Visitor thumbs up/down on this answer, set via /api/assistant/feedback.
   */
  feedback?: ('up' | 'down') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every URL on the site. Nothing reaches Google until someone submits it from Content indexing or Indexing -- new rows arrive as Not submitted, which means search engines may crawl the page but are told not to list it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-index".
 */
export interface PageIndex {
  id: number;
  /**
   * Stable key set by the scan (computed: type:service:state:city, entity: type:docId). Not hand-editable.
   */
  pageKey: string;
  /**
   * The live URL this row controls.
   */
  path: string;
  pageType:
    | 'service-pillar'
    | 'service-state'
    | 'service-city'
    | 'state-hub'
    | 'city-hub'
    | 'brand-pillar'
    | 'brand-state'
    | 'brand-city-directory'
    | 'clinic'
    | 'guide'
    | 'news'
    | 'static'
    | 'question';
  /**
   * Not submitted (default): search engines can crawl the page but are told not to list it, and it is waiting for a batch. Submitted: it goes into the sitemap as soon as it is live on the site. Never submit: held back permanently, and the batch tools skip it.
   */
  indexMode: 'queued' | 'indexed' | 'excluded';
  /**
   * The answer both the page tag and the sitemap use. Only true when someone submitted it AND it is live on the site.
   */
  indexed?: boolean | null;
  /**
   * Is there anything real to show here? For a clinic, guide or article: the document is published (and approved). For a listing page: at least one published clinic matches it. Written by the scan. When this is false the page stays out of Google no matter what anyone sets above.
   */
  publishable?: boolean | null;
  /**
   * Does this page have enough behind it to be worth a search result? Bar per page type: service-city 5, brand-city-directory 5, city-hub 3, service-state 10, brand-state 10, state-hub 10, service-pillar 25, brand-pillar 25, clinic 1, guide 1, news 1, static 1, question 1. Advice only, not a block: a thin page can still be submitted on purpose.
   */
  meetsThreshold?: boolean | null;
  /**
   * When this URL was batched in. Empty while queued or excluded.
   */
  indexedAt?: string | null;
  /**
   * Which batch flipped this row to Indexed. Filter on it to review or roll back one batch.
   */
  batchLabel?: string | null;
  /**
   * For entity pages: the collection the URL comes from. Empty for computed pages.
   */
  sourceCollection?: string | null;
  /**
   * For entity pages: the source document id, so this row links back to the doc.
   */
  sourceId?: string | null;
  serviceSlug?: string | null;
  brandSlug?: string | null;
  stateSlug?: string | null;
  citySlug?: string | null;
  /**
   * Published clinics matching this page at the last scan. Entity pages carry 1 (they are gated by publish status, not volume).
   */
  dataCount?: number | null;
  hasData?: boolean | null;
  /**
   * Triage flag. Newly discovered URLs land unacknowledged so they show up as "new since you last looked". Batching a row in or excluding it acknowledges it automatically; you can also acknowledge to mean "seen, leaving it queued for now".
   */
  acknowledged?: boolean | null;
  firstSeenWithData?: string | null;
  lastScannedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Clinic profile claims awaiting review. Approving a claim promotes the claimant to a clinic owner account and marks the profile claimed. Rows with a "Requested Clinic Name" are new-listing requests: no profile exists yet, and approving creates it as a draft clinic first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims".
 */
export interface Claim {
  id: number;
  claimType: 'clinic';
  /**
   * The clinic profile being claimed.
   */
  targetClinic?: (number | null) | Clinic;
  /**
   * New listing request: no existing clinic matched, so approving creates this clinic as a draft.
   */
  requestedClinicName?: string | null;
  /**
   * City for the new clinic record.
   */
  requestedCity?: string | null;
  /**
   * Two-letter state code for the new clinic record.
   */
  requestedState?: string | null;
  claimantName: string;
  claimantEmail: string;
  claimantPhone?: string | null;
  directPhone?: string | null;
  directEmail?: string | null;
  /**
   * True once the claimant confirmed the code we emailed. If false, they never proved they own this inbox — verify manually before approving.
   */
  emailVerified?: boolean | null;
  /**
   * exact = same email on file, domain = same website/email domain, none = no match (extra caution), unknown = no contact on file to compare.
   */
  emailMatch?: ('exact' | 'domain' | 'none' | 'unknown') | null;
  verificationCode?: string | null;
  verificationCodeExpiry?: string | null;
  verifyToken?: string | null;
  /**
   * e.g. Owner, Medical Director, Lead Injector
   */
  roleAtPractice: string;
  /**
   * Required for provider claims.
   */
  licenseNumber?: string | null;
  /**
   * Optional NPI for provider claims.
   */
  npiNumber?: string | null;
  /**
   * Website, LLC docs, or other proof for clinic claims.
   */
  businessProof?: string | null;
  /**
   * Any additional context from the claimant.
   */
  message?: string | null;
  status: 'new' | 'approved' | 'rejected';
  /**
   * Admin who reviewed this claim.
   */
  reviewedBy?: (number | null) | User;
  /**
   * Internal notes visible only to admins.
   */
  reviewNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Claim-invite emails sent to clinic owners. Sent from the Claims page control center. Unsubscribed emails are never contacted again.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claim-invites".
 */
export interface ClaimInvite {
  id: number;
  /**
   * The clinic this invite points at.
   */
  targetClinic?: (number | null) | Clinic;
  /**
   * Recipient address (from the clinic record at send time).
   */
  email: string;
  status: 'sent' | 'claimed' | 'unsubscribed';
  /**
   * How many times the invite has been sent (initial + resends).
   */
  sendCount?: number | null;
  /**
   * When the most recent invite email went out.
   */
  lastSentAt?: string | null;
  /**
   * Admin who sent the most recent invite.
   */
  sentBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter and waitlist subscribers. Only confirmed subscribers receive emails. No health information is stored here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  /**
   * Optional display name (first name or full).
   */
  name?: string | null;
  /**
   * Double opt-in flow. Only confirmed subscribers receive newsletters.
   */
  status: 'pending' | 'confirmed' | 'unsubscribed';
  source: 'waitlist' | 'quiz' | 'footer' | 'guide' | 'other';
  /**
   * Determines which emails this subscriber receives.
   */
  interestType: 'general' | 'city-waitlist';
  /**
   * City the visitor asked about (city-waitlist only, e.g. "Houston").
   */
  cityTag?: string | null;
  /**
   * Two-letter state code for the city-waitlist interest.
   */
  stateCode?: string | null;
  /**
   * Service of interest, if any.
   */
  serviceTag?: string | null;
  /**
   * UUID used in confirm and unsubscribe links. Never share externally.
   */
  confirmToken?: string | null;
  confirmTokenExpiresAt?: string | null;
  /**
   * When the visitor submitted the signup form.
   */
  optInAt?: string | null;
  /**
   * When the visitor clicked the confirmation link.
   */
  confirmedAt?: string | null;
  /**
   * When the subscriber clicked the unsubscribe link.
   */
  unsubscribedAt?: string | null;
  /**
   * IP address at signup time. Consent audit log only. Not shared.
   */
  ipAtSignup?: string | null;
  /**
   * Set once a go-live email has been sent to this subscriber.
   */
  notified?: boolean | null;
  /**
   * Set when a logged-in patient subscribes.
   */
  linkedUser?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Video testimonials shown in the "On video" homepage section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-testimonials".
 */
export interface VideoTestimonial {
  id: number;
  /**
   * Short title for the video, e.g. "How to spot an overfilled lip".
   */
  caption: string;
  /**
   * Creator name and credentials, e.g. "Dr. Lena Park, MD".
   */
  creator: string;
  /**
   * Upload the video thumbnail image (9:16 portrait crop, ideally 450×800px).
   */
  thumbnail: number | Media;
  /**
   * Full URL to the video. Examples: https://www.instagram.com/reel/ABC123/ · https://www.tiktok.com/@user/video/123 · https://youtu.be/ABC123
   */
  href: string;
  platform: 'instagram' | 'tiktok' | 'youtube';
  /**
   * Display duration string, e.g. "0:47" or "1:02".
   */
  duration: string;
  /**
   * Show this video on the site.
   */
  active?: boolean | null;
  /**
   * Lower number = shown first.
   */
  sortRank?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Social proof posts shown in the "What they're saying" homepage section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts".
 */
export interface SocialPost {
  id: number;
  platform: 'x' | 'instagram' | 'facebook' | 'reddit' | 'google';
  /**
   * The review or post text (the quote shown on screen).
   */
  quote: string;
  /**
   * Author display name, e.g. "Caroline M.".
   */
  author: string;
  /**
   * Username or handle, e.g. "@carolinem_nyc" or "u/skin_curious".
   */
  handle: string;
  /**
   * Upload the author avatar photo. Leave blank to use a default placeholder.
   */
  avatar?: (number | null) | Media;
  /**
   * Link to the original post. Use # if not applicable.
   */
  href?: string | null;
  /**
   * Display date string, e.g. "Mar 2026".
   */
  date: string;
  /**
   * Like or upvote count. Set to 0 to hide the count.
   */
  likes?: number | null;
  /**
   * Star rating 1–5. Only shown for Google reviews.
   */
  rating?: number | null;
  /**
   * Show as a large featured pull-quote card (always visible, not filterable).
   */
  featured?: boolean | null;
  /**
   * Include in the site social feed.
   */
  active?: boolean | null;
  /**
   * Lower number = shown first.
   */
  sortRank?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Internal links awaiting review before insertion: editorial-seeded (from handoff content) or AI-discovered (Kimi K3 via OpenRouter). Approving inserts a real inline link into the source Guide/News body with a hover preview card.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal-link-suggestions".
 */
export interface InternalLinkSuggestion {
  id: number;
  /**
   * The Guide or News article this link will be inserted into.
   */
  source:
    | {
        relationTo: 'guides';
        value: number | Guide;
      }
    | {
        relationTo: 'news';
        value: number | News;
      };
  /**
   * Exact substring that must appear verbatim in the source body -- this is what becomes the clickable link.
   */
  anchorText: string;
  targetType?: ('guide' | 'news' | 'service' | 'brand') | null;
  targetSlug: string;
  targetUrl: string;
  /**
   * Shown in the hover preview card.
   */
  targetTitle?: string | null;
  /**
   * Shown in the hover preview card.
   */
  targetExcerpt?: string | null;
  /**
   * Why the agent (or editorial content) suggested this link -- shown to the admin reviewer for trust.
   */
  reasoning?: string | null;
  origin: 'editorial-seed' | 'ai-discovery';
  status: 'pending' | 'approved' | 'rejected';
  /**
   * Set automatically once the link is actually inserted into the body.
   */
  insertedAt?: string | null;
  /**
   * Set if approval succeeded but insertion failed (e.g. anchor text no longer matches the body).
   */
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'clinics';
        value: number | Clinic;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'photos';
        value: number | Photo;
      } | null)
    | ({
        relationTo: 'qa';
        value: number | Qa;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'medical-reviewers';
        value: number | MedicalReviewer;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'before-after-cases';
        value: number | BeforeAfterCase;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'data-alerts';
        value: number | DataAlert;
      } | null)
    | ({
        relationTo: 'export-jobs';
        value: number | ExportJob;
      } | null)
    | ({
        relationTo: 'scan-jobs';
        value: number | ScanJob;
      } | null)
    | ({
        relationTo: 'assistant-logs';
        value: number | AssistantLog;
      } | null)
    | ({
        relationTo: 'page-index';
        value: number | PageIndex;
      } | null)
    | ({
        relationTo: 'claims';
        value: number | Claim;
      } | null)
    | ({
        relationTo: 'claim-invites';
        value: number | ClaimInvite;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'zip-codes';
        value: number | ZipCode;
      } | null)
    | ({
        relationTo: 'video-testimonials';
        value: number | VideoTestimonial;
      } | null)
    | ({
        relationTo: 'social-posts';
        value: number | SocialPost;
      } | null)
    | ({
        relationTo: 'internal-link-suggestions';
        value: number | InternalLinkSuggestion;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  linkedClinic?: T;
  linkedBrand?: T;
  savedClinics?: T;
  quizRecommendation?: T;
  setupToken?: T;
  setupTokenExpiry?: T;
  emailVerified?: T;
  verificationCode?: T;
  verificationCodeExpiry?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  tagline?: T;
  shortDescription?: T;
  bodyAreas?: T;
  relatedBrands?: T;
  guide?: T;
  avgPriceFromUsd?: T;
  avgPriceToUsd?: T;
  priceUnit?: T;
  iconSlug?: T;
  painIndex?: T;
  longevityLabel?: T;
  longevityMonthsMin?: T;
  longevityMonthsMax?: T;
  downtimeLabel?: T;
  downtimeHoursMax?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  manufacturer?: T;
  category?: T;
  tagline?: T;
  shortDescription?: T;
  guide?: T;
  avgPriceFromUsd?: T;
  avgPriceToUsd?: T;
  priceUnit?: T;
  iconSlug?: T;
  longevityLabel?: T;
  longevityMonthsMin?: T;
  longevityMonthsMax?: T;
  downtimeLabel?: T;
  downtimeHoursMax?: T;
  websiteUrl?: T;
  logoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  state?: T;
  parent?: T;
  latitude?: T;
  longitude?: T;
  imageUrl?: T;
  providerCount?: T;
  sortRank?: T;
  featured?: T;
  isLive?: T;
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinics_select".
 */
export interface ClinicsSelect<T extends boolean = true> {
  clinicName?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  clinicType?: T;
  acceptsInsurance?: T;
  paymentMethods?: T;
  amenities?: T;
  aggregateRating?: T;
  aggregateRatingCount?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  zip?: T;
  neighborhood?: T;
  county?: T;
  country?: T;
  latitude?: T;
  longitude?: T;
  googlePlaceId?: T;
  googleMapsUrl?: T;
  directionsUrl?: T;
  appleMapsUrl?: T;
  phone?: T;
  email?: T;
  emailPublic?: T;
  websiteUrl?: T;
  bookingUrl?: T;
  instagramUrl?: T;
  tiktokUrl?: T;
  facebookUrl?: T;
  linkedinUrl?: T;
  youtubeUrl?: T;
  hoursJson?: T;
  brandsOffered?: T;
  servicesOffered?: T;
  startingPrice?: T;
  logoUrl?: T;
  clinicPhotoUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  hasPhoto?: T;
  photos?: T;
  subscriptionTier?: T;
  subscriptionStatus?: T;
  claimed?: T;
  claimedBy?: T;
  clinicId?: T;
  importBatch?: T;
  lastScrapedDate?: T;
  sourceUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  status?: T;
  noindex?: T;
  publishedAt?: T;
  dataConfidence?: T;
  needsManualReview?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  reviewId?: T;
  clinic?: T;
  rating?: T;
  title?: T;
  excerpt?: T;
  text?: T;
  publishStatus?: T;
  serviceTag?: T;
  reviewDate?: T;
  sourcePlatform?: T;
  sourceReviewId?: T;
  sourceUrl?: T;
  attributionRequired?: T;
  responseFromProvider?: T;
  responseDate?: T;
  matchConfidence?: T;
  needsManualReview?: T;
  importBatch?: T;
  moderationStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  photoId?: T;
  clinic?: T;
  serviceTag?: T;
  photoUrl?: T;
  type?: T;
  pairId?: T;
  weeksPostTreatment?: T;
  caption?: T;
  consentDocumented?: T;
  sourcePlatform?: T;
  sourceUrl?: T;
  importBatch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "qa_select".
 */
export interface QaSelect<T extends boolean = true> {
  qaId?: T;
  slug?: T;
  status?: T;
  questionTitle?: T;
  questionText?: T;
  answeredByName?: T;
  answerText?: T;
  serviceTag?: T;
  cityTag?: T;
  sourcePlatform?: T;
  sourceUrl?: T;
  date?: T;
  submitterEmail?: T;
  importBatch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  fullName?: T;
  slug?: T;
  role?: T;
  bio?: T;
  photoUrl?: T;
  linkedinUrl?: T;
  twitterUrl?: T;
  articleCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-reviewers_select".
 */
export interface MedicalReviewersSelect<T extends boolean = true> {
  fullName?: T;
  slug?: T;
  credentials?: T;
  title?: T;
  city?: T;
  state?: T;
  bio?: T;
  photoUrl?: T;
  npiNumber?: T;
  boardCertifications?:
    | T
    | {
        name?: T;
        id?: T;
      };
  linkedinUrl?: T;
  reviewedCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  lede?: T;
  excerpt?: T;
  coverImage?: T;
  coverImageUrl?: T;
  category?: T;
  relatedService?: T;
  readTimeMin?: T;
  sourcesCount?: T;
  author?: T;
  medicalReviewer?: T;
  lastMedicallyReviewed?: T;
  body?: T;
  answerSnippet?: T;
  atAGlance?: T;
  faq?: T;
  sources?: T;
  internalLinks?: T;
  linkDiscoveryScannedAt?: T;
  focusKeyword?: T;
  faqs?: T;
  featured?: T;
  publishedAt?: T;
  status?: T;
  reviewStatus?: T;
  indexState?: T;
  nofollow?: T;
  importBatch?: T;
  approvedAt?: T;
  approvedBy?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  coverImageUrl?: T;
  body?: T;
  answerSnippet?: T;
  atAGlance?: T;
  faq?: T;
  sources?: T;
  internalLinks?: T;
  linkDiscoveryScannedAt?: T;
  focusKeyword?: T;
  category?: T;
  author?: T;
  medicalReviewer?: T;
  publishedAt?: T;
  relatedService?: T;
  status?: T;
  featured?: T;
  reviewStatus?: T;
  indexState?: T;
  nofollow?: T;
  importBatch?: T;
  approvedAt?: T;
  approvedBy?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  answerDetail?: T;
  scope?: T;
  service?: T;
  brand?: T;
  guide?: T;
  location?: T;
  clinicType?: T;
  relatedGuide?: T;
  offLabel?: T;
  safetyFlag?: T;
  sortRank?: T;
  stableId?: T;
  reviewStatus?: T;
  importBatch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-after-cases_select".
 */
export interface BeforeAfterCasesSelect<T extends boolean = true> {
  caseTitle?: T;
  beforePhotoUrl?: T;
  afterPhotoUrl?: T;
  serviceTag?: T;
  weeksPost?: T;
  city?: T;
  state?: T;
  patientNote?: T;
  consentGranted?: T;
  featured?: T;
  sortRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  patientName?: T;
  patientEmail?: T;
  patientPhone?: T;
  clinic?: T;
  service?: T;
  serviceTag?: T;
  preferredDate?: T;
  preferredTime?: T;
  message?: T;
  consentToContact?: T;
  status?: T;
  source?: T;
  utm?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  placement?: T;
  scope?: T;
  service?: T;
  state?: T;
  city?: T;
  zipScope?: T;
  zipRadiusMiles?: T;
  clinic?: T;
  featuredRank?: T;
  bannerImage?: T;
  bannerLinkUrl?: T;
  bannerAltText?: T;
  startDate?: T;
  endDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  collectionSlug?: T;
  documentId?: T;
  documentTitle?: T;
  userEmail?: T;
  userId?: T;
  summary?: T;
  changedFields?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-alerts_select".
 */
export interface DataAlertsSelect<T extends boolean = true> {
  alertKey?: T;
  type?: T;
  severity?: T;
  message?: T;
  collectionSlug?: T;
  documentId?: T;
  relatedId?: T;
  source?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "export-jobs_select".
 */
export interface ExportJobsSelect<T extends boolean = true> {
  collectionSlug?: T;
  status?: T;
  filters?: T;
  filterSummary?: T;
  totalRows?: T;
  processedRows?: T;
  fileName?: T;
  fileUrl?: T;
  fileSizeBytes?: T;
  error?: T;
  startedBy?: T;
  startedAt?: T;
  finishedAt?: T;
  heartbeatAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scan-jobs_select".
 */
export interface ScanJobsSelect<T extends boolean = true> {
  status?: T;
  phase?: T;
  trigger?: T;
  totalRows?: T;
  processedRows?: T;
  createdRows?: T;
  updatedRows?: T;
  lostDataRows?: T;
  failedRows?: T;
  unmappedClinics?: T;
  bySource?: T;
  indexedNow?: T;
  queuedNow?: T;
  marketsFlippedLive?: T;
  marketsFlippedComingSoon?: T;
  error?: T;
  startedBy?: T;
  startedAt?: T;
  finishedAt?: T;
  heartbeatAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistant-logs_select".
 */
export interface AssistantLogsSelect<T extends boolean = true> {
  query?: T;
  ip?: T;
  tokensIn?: T;
  tokensOut?: T;
  estimatedCostUsd?: T;
  toolsUsed?: T;
  flagged?: T;
  feedback?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-index_select".
 */
export interface PageIndexSelect<T extends boolean = true> {
  pageKey?: T;
  path?: T;
  pageType?: T;
  indexMode?: T;
  indexed?: T;
  publishable?: T;
  meetsThreshold?: T;
  indexedAt?: T;
  batchLabel?: T;
  sourceCollection?: T;
  sourceId?: T;
  serviceSlug?: T;
  brandSlug?: T;
  stateSlug?: T;
  citySlug?: T;
  dataCount?: T;
  hasData?: T;
  acknowledged?: T;
  firstSeenWithData?: T;
  lastScannedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claims_select".
 */
export interface ClaimsSelect<T extends boolean = true> {
  claimType?: T;
  targetClinic?: T;
  requestedClinicName?: T;
  requestedCity?: T;
  requestedState?: T;
  claimantName?: T;
  claimantEmail?: T;
  claimantPhone?: T;
  directPhone?: T;
  directEmail?: T;
  emailVerified?: T;
  emailMatch?: T;
  verificationCode?: T;
  verificationCodeExpiry?: T;
  verifyToken?: T;
  roleAtPractice?: T;
  licenseNumber?: T;
  npiNumber?: T;
  businessProof?: T;
  message?: T;
  status?: T;
  reviewedBy?: T;
  reviewNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "claim-invites_select".
 */
export interface ClaimInvitesSelect<T extends boolean = true> {
  targetClinic?: T;
  email?: T;
  status?: T;
  sendCount?: T;
  lastSentAt?: T;
  sentBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  status?: T;
  source?: T;
  interestType?: T;
  cityTag?: T;
  stateCode?: T;
  serviceTag?: T;
  confirmToken?: T;
  confirmTokenExpiresAt?: T;
  optInAt?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  ipAtSignup?: T;
  notified?: T;
  linkedUser?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zip-codes_select".
 */
export interface ZipCodesSelect<T extends boolean = true> {
  zip?: T;
  city?: T;
  state?: T;
  county?: T;
  location?: T;
  lat?: T;
  lng?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video-testimonials_select".
 */
export interface VideoTestimonialsSelect<T extends boolean = true> {
  caption?: T;
  creator?: T;
  thumbnail?: T;
  href?: T;
  platform?: T;
  duration?: T;
  active?: T;
  sortRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-posts_select".
 */
export interface SocialPostsSelect<T extends boolean = true> {
  platform?: T;
  quote?: T;
  author?: T;
  handle?: T;
  avatar?: T;
  href?: T;
  date?: T;
  likes?: T;
  rating?: T;
  featured?: T;
  active?: T;
  sortRank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internal-link-suggestions_select".
 */
export interface InternalLinkSuggestionsSelect<T extends boolean = true> {
  source?: T;
  anchorText?: T;
  targetType?: T;
  targetSlug?: T;
  targetUrl?: T;
  targetTitle?: T;
  targetExcerpt?: T;
  reasoning?: T;
  origin?: T;
  status?: T;
  insertedAt?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Control which services, locations, and guides appear in the navigation mega menu. Changes go live within 60 seconds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-config".
 */
export interface HeaderConfig {
  id: number;
  /**
   * Pick up to 10 product brands to show in the Brands section of the menu.
   */
  featuredBrands?: (number | Brand)[] | null;
  /**
   * Pick up to 10 services to show in the Services section of the menu.
   */
  featuredServices?: (number | Service)[] | null;
  /**
   * Pick any mix of cities and states. These appear in the Find section.
   */
  featuredLocations?: (number | Location)[] | null;
  /**
   * Pick up to 10 guides to show in the Learn section of the menu.
   */
  featuredGuides?: (number | Guide)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Search visibility and the sitewide link preview (title/description/image shown when the homepage link is shared in Slack, email, iMessage, etc).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: number;
  /**
   * When on: crawlers can still crawl the site, but every page carries a noindex meta tag so search engines won't list it. Turn off when the site is ready to go live.
   */
  siteNoindex?: boolean | null;
  /**
   * Controls the floating Chat button (bottom-right, on every page). The old "Ask anything" hero search box has been removed for good, this is the only AI entry point left. Turn off to hide the Chat button entirely, e.g. while it is still in "coming soon" mode.
   */
  chatWidgetEnabled?: boolean | null;
  /**
   * Title shown when the homepage link is shared anywhere (Slack, email, iMessage, etc). Leave blank to use the built-in default.
   */
  metaTitle?: string | null;
  /**
   * Description shown under the title in link previews. Leave blank to use the built-in default.
   */
  metaDescription?: string | null;
  /**
   * Image shown in link previews. Recommended 1200x630. Leave blank to use the default logo mark.
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-config_select".
 */
export interface HeaderConfigSelect<T extends boolean = true> {
  featuredBrands?: T;
  featuredServices?: T;
  featuredLocations?: T;
  featuredGuides?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  siteNoindex?: T;
  chatWidgetEnabled?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}